const TURKISH_CHARACTERS = /[âçğıîöşûüÂÇĞİÎÖŞÛÜ]/u;

const PHRASES: readonly (readonly [string, string])[] = [
  ["TURKIYE GENELI", "NATIONWIDE, TURKEY"],
  ["IC VE DIS HATLAR", "DOMESTIC AND INTERNATIONAL TERMINALS"],
  ["DIS HATLAR TERMINALI", "INTERNATIONAL TERMINAL"],
  ["ATIK SU ARITMA TESISI", "WASTEWATER TREATMENT PLANT"],
  ["ATIKSU ARITMA TESISI", "WASTEWATER TREATMENT PLANT"],
  ["ATIKSU ARITMA", "WASTEWATER TREATMENT"],
  ["ARITMA TESISLERI", "TREATMENT FACILITIES"],
  ["ARITMA TESISI", "TREATMENT PLANT"],
  ["TERMIK SANTRALI", "THERMAL POWER PLANT"],
  ["DOGALGAZ CEVRIM SANTRALI", "NATURAL GAS COMBINED-CYCLE POWER PLANT"],
  ["BIYOGAZ ENERJI SANTRALI", "BIOGAS POWER PLANT"],
  ["GUNES ENERJI SANTRALI", "SOLAR POWER PLANT"],
  ["RUZGAR ENERJI SANTRALI", "WIND POWER PLANT"],
  ["HIDROELEKTRIK SANTRALI", "HYDROELECTRIC POWER PLANT"],
  ["SPOR KOMPLEKSI", "SPORTS COMPLEX"],
  ["SAGLIK KAMPUSU", "HEALTHCARE CAMPUS"],
  ["DEVLET HASTANESI", "STATE HOSPITAL"],
  ["KADIN DOGUM HASTANESI", "MATERNITY HOSPITAL"],
  ["HIZMET BINASI", "SERVICE BUILDING"],
  ["IDARE BINASI", "ADMINISTRATION BUILDING"],
  ["IS MERKEZI", "BUSINESS CENTRE"],
  ["IS MRKZ.", "BUSINESS CENTRE"],
  ["ORGANIZE SANAYI BOLGESI", "ORGANISED INDUSTRIAL ZONE"],
  ["ORG.SAN.BOL.", "ORGANISED INDUSTRIAL ZONE"],
  ["ALTIN MADENI", "GOLD MINE"],
  ["KATI ATIK", "SOLID WASTE"],
  ["SOSYAL HIZMETLER", "SOCIAL SERVICES"],
  ["ASKERI PROTOKOL", "MILITARY PROTOCOL"],
  ["BORU HATTI", "PIPELINE"],
  ["VERI MERKEZI", "DATA CENTRE"],
  ["GENEL MUDURLUK", "HEADQUARTERS"],
  ["DOLUM TESISI", "FILLING PLANT"],
  ["ORGANIZE SANAYI SITESI", "ORGANISED INDUSTRIAL ESTATE"],
  ["SANAYI SITESI", "INDUSTRIAL ESTATE"],
  ["YASAM MERKEZI", "LIFESTYLE CENTRE"],
  ["DIS HASTANESI", "DENTAL HOSPITAL"],
  ["SEHIR HASTANESI", "CITY HOSPITAL"],
  ["TIP HASTANESI", "MEDICAL HOSPITAL"],
  ["VERGI DAIRESI", "TAX OFFICE"],
  ["ALIŞVERIS MERKEZI", "SHOPPING CENTRE"],
  ["ALISVERIS MERKEZI", "SHOPPING CENTRE"],
  ["OGRENCI YURDU", "STUDENT RESIDENCE"],
  ["KULTUR MERKEZI", "CULTURAL CENTRE"],
  ["KONGRE MERKEZI", "CONVENTION CENTRE"],
  ["LOJISTIK MERKEZI", "LOGISTICS CENTRE"],
  ["OPERASYON MERKEZI", "OPERATIONS CENTRE"],
  ["ARASTIRMA MERKEZI", "RESEARCH CENTRE"],
  ["EGITIM MERKEZI", "TRAINING CENTRE"],
  ["YONETIM BINASI", "ADMINISTRATION BUILDING"],
  ["MAHKEME BINASI", "COURTHOUSE"],
  ["ADLIYE SARAYI", "COURTHOUSE"],
  ["TOPLU KONUT", "HOUSING DEVELOPMENT"],
  ["SANAYI TESISI", "INDUSTRIAL FACILITY"],
  ["URETIM TESISI", "PRODUCTION FACILITY"],
  ["DEPOLAMA TESISI", "STORAGE FACILITY"],
  ["SU ARITMA", "WATER TREATMENT"],
  ["KUTUPHANESI", "LIBRARY"],
  ["KUTUPHANE", "LIBRARY"],
  ["ILAHIYAT FAKULTESI", "FACULTY OF THEOLOGY"],
  ["GELISIM PROJESI", "DEVELOPMENT PROJECT"],
  ["GENISLEME PROJESI", "EXPANSION PROJECT"],
  ["KONUT PROJESI", "RESIDENTIAL PROJECT"],
  ["OFIS PROJESI", "OFFICE PROJECT"],
  ["GES PROJESI", "SOLAR POWER PROJECT"],
  ["HES PROJESI", "HYDROELECTRIC POWER PROJECT"],
  ["YENI ONKOLOJI BINASI", "NEW ONCOLOGY BUILDING"],
  ["TASIYICI SISTEMLER", "SUPPORT SYSTEMS"],
  ["ORTA GERILIM", "MEDIUM VOLTAGE"],
  ["ALCAK GERILIM", "LOW VOLTAGE"],
  ["KIMYASAL VE BIYOLOJIK", "CHEMICAL AND BIOLOGICAL"],
  ["OTO YAN SANAYI", "AUTOMOTIVE COMPONENTS"],
  ["URETIM TESISI", "PRODUCTION FACILITY"],
  ["ISLETMESI PROJESI", "FACILITY PROJECT"],
  ["FABRIKA ISLERI", "FACTORY WORKS"],
  ["SUBELERI", "BRANCHES"],
  ["YATAKLI", "BED"],
  ["ENTEGRE", "INTEGRATED"],
  ["URETIM", "PRODUCTION"],
  ["ISLETMESI", "FACILITY"],
  ["ISLERI", "WORKS"],
  ["CATI", "ROOFTOP"],
  ["GUBRE", "FERTILISER"],
  ["BOYA", "PAINT"],
  ["YURT", "DORMITORY"],
  ["SAGLIK", "HEALTHCARE"],
  ["KISIM", "SECTION"],
  ["GENEL KUTUPHANE", "GENERAL LIBRARY"],
  ["GENEL KUTUP", "GENERAL LIBRARY"],
  ["YENI", "NEW"],
  ["VE", "AND"],
  ["HAVALIMANI", "AIRPORT"],
  ["HAVAALANI", "AIRPORT"],
  ["H.LIMANI", "AIRPORT"],
  ["HASTAHANESI", "HOSPITAL"],
  ["HASTANESI", "HOSPITAL"],
  ["HASTAHANE", "HOSPITAL"],
  ["HASTANE", "HOSPITAL"],
  ["HAST.", "HOSPITAL"],
  ["FABRIKASI", "FACTORY"],
  ["FABRIKA", "FACTORY"],
  ["FABR.", "FACTORY"],
  ["FABR", "FACTORY"],
  ["KONUTLARI", "RESIDENCES"],
  ["EVLERI", "RESIDENCES"],
  ["VILALARI", "VILLAS"],
  ["KONUT", "RESIDENTIAL"],
  ["OFISLERI", "OFFICES"],
  ["OFIS", "OFFICE"],
  ["AVM", "SHOPPING CENTRE"],
  ["BINASI", "BUILDING"],
  ["BINALARI", "BUILDINGS"],
  ["SANTRALI", "POWER PLANT"],
  ["TESISLERI", "FACILITIES"],
  ["TESISI", "FACILITY"],
  ["TESIS", "FACILITY"],
  ["PROJELERI", "PROJECTS"],
  ["PROJESI", "PROJECT"],
  ["PROJ.", "PROJECT"],
  ["PROJE", "PROJECT"],
  ["PRJ", "PROJECT"],
  ["UNIVERSITESI", "UNIVERSITY"],
  ["UNI.", "UNIVERSITY"],
  ["UNI", "UNIVERSITY"],
  ["KOLEJI", "COLLEGE"],
  ["KAMPUSU", "CAMPUS"],
  ["KAMPUS", "CAMPUS"],
  ["FAKULTESI", "FACULTY"],
  ["MAGAZASI", "STORE"],
  ["LIMANI", "PORT"],
  ["KORFEZI", "BAY"],
  ["YALISI", "WATERFRONT MANSION"],
  ["ADLIYE", "COURTHOUSE"],
  ["BELEDIYESI", "MUNICIPALITY"],
  ["MERKEZI", "CENTRE"],
  ["MAHALLESI", "NEIGHBOURHOOD"],
  ["MAHALLE", "NEIGHBOURHOOD"],
  ["KENT", "CITY"],
  ["SEHIR", "CITY"],
  ["VADI", "VALLEY"],
  ["YASAM", "LIFESTYLE"],
  ["BATI", "WEST"],
  ["DOGU", "EAST"],
  ["KUZEY", "NORTH"],
  ["GUNEY", "SOUTH"],
  ["MAVI", "BLUE"],
  ["YESIL", "GREEN"],
  ["GENISLEME", "EXPANSION"],
  ["GELISIM", "DEVELOPMENT"],
  ["ASKERI", "MILITARY"],
  ["SARAYI", "PALACE"],
  ["KULESI", "TOWER"],
  ["STADYUMU", "STADIUM"],
  ["STADI", "STADIUM"],
  ["GIDA", "FOOD"],
  ["KIMYA", "CHEMICALS"],
  ["ILAC", "PHARMACEUTICALS"],
  ["CIMENTO", "CEMENT"],
  ["SUT", "DAIRY"],
  ["KAGIT", "PAPER"],
  ["TEKSTIL", "TEXTILE"],
  ["TARIM", "AGRICULTURE"],
  ["TURIZM", "TOURISM"],
  ["OTELI", "HOTEL"],
  ["OTEL", "HOTEL"],
  ["TERMINALI", "TERMINAL"],
  ["ISTASYONU", "STATION"],
  ["SANTIYESI", "CONSTRUCTION SITE"],
  ["TERSANESI", "SHIPYARD"],
  ["DEPOSU", "WAREHOUSE"],
  ["DEPO", "WAREHOUSE"],
  ["OKULU", "SCHOOL"],
  ["OKUL", "SCHOOL"],
  ["SANAYI", "INDUSTRIAL"],
  ["ENERJI", "ENERGY"],
  ["PLASTIK", "PLASTICS"],
  ["CELIK", "STEEL"],
  ["HALI", "CARPET"],
  ["IPLIK", "YARN"],
  ["OTOMOTIV", "AUTOMOTIVE"],
  ["INSAAT", "CONSTRUCTION"],
  ["YAPI", "CONSTRUCTION"],
  ["MUHENDISLIK", "ENGINEERING"],
  ["SISTEMLER", "SYSTEMS"],
  ["TASIYICI", "SUPPORT"],
  ["AGAC", "WOOD"],
  ["KIMYASAL", "CHEMICAL"],
  ["BIYOLOJIK", "BIOLOGICAL"],
  ["ALUMINYUM", "ALUMINIUM"],
  ["KOZMETIK", "COSMETICS"],
  ["BOR", "BORON"],
  ["ASIT", "ACID"],
  ["DESARJ", "DISCHARGE"],
  ["MAKINA", "MACHINERY"],
  ["MOBILYA", "FURNITURE"],
  ["SERAMIK", "CERAMICS"],
  ["ELEKTRONIK", "ELECTRONICS"],
  ["DONDURMA", "ICE CREAM"],
  ["KUYUMCULUK", "JEWELLERY"],
  ["LASTIK", "TYRE"],
  ["URUNLERI", "PRODUCTS"],
  ["SEKER", "SUGAR"],
  ["KOMPLEKSI", "COMPLEX"],
  ["MUDURLUK", "DIRECTORATE"],
  ["DOLUM", "FILLING"],
  ["TERMINAL", "TERMINAL"],
  ["TURKIYE", "TURKEY"],
  ["OZBEKISTAN", "UZBEKISTAN"],
  ["AZERBAYCAN", "AZERBAIJAN"],
  ["KAZAKISTAN", "KAZAKHSTAN"],
  ["RUSYA", "RUSSIA"],
  ["IRAK", "IRAQ"],
  ["LIBYA", "LIBYA"],
  ["MISIR", "EGYPT"],
  ["HOLLANDA", "NETHERLANDS"],
  ["ALMANYA", "GERMANY"],
  ["KIBRIS", "CYPRUS"],
  ["ROMANYA", "ROMANIA"],
  ["CEZAYIR", "ALGERIA"],
  ["TURKMENISTAN", "TURKMENISTAN"],
  ["NIJERYA", "NIGERIA"],
  ["UKRAYNA", "UKRAINE"],
  ["MACARISTAN", "HUNGARY"],
  ["GURCISTAN", "GEORGIA"],
  ["YUNANISTAN", "GREECE"],
  ["LUBNAN", "LEBANON"],
  ["TACIKISTAN", "TAJIKISTAN"],
  ["AFGANISTAN", "AFGHANISTAN"],
  ["KKTC", "NORTHERN CYPRUS"],
] as const;

const ORDERED_PHRASES = [...PHRASES].sort((a, b) => b[0].length - a[0].length);

function replacePhrase(value: string, source: string, target: string): string {
  const escaped = source.replace(/[.*+?^${}()|[\]\\]/gu, "\\$&");
  return value.replace(new RegExp(`(?<![\\p{L}\\p{N}])${escaped}(?![\\p{L}\\p{N}])`, "gu"), target);
}

export function transliterateTurkish(value: string): string {
  return value
    .replace(/[Ââ]/gu, (character) => (character === "Â" ? "A" : "a"))
    .replace(/[Çç]/gu, (character) => (character === "Ç" ? "C" : "c"))
    .replace(/[Ğğ]/gu, (character) => (character === "Ğ" ? "G" : "g"))
    .replace(/[Îî]/gu, (character) => (character === "Î" ? "I" : "i"))
    .replace(/[İIıi]/gu, (character) => (character === "İ" || character === "I" ? "I" : "i"))
    .replace(/[Öö]/gu, (character) => (character === "Ö" ? "O" : "o"))
    .replace(/[Şş]/gu, (character) => (character === "Ş" ? "S" : "s"))
    .replace(/[Ûû]/gu, (character) => (character === "Û" ? "U" : "u"))
    .replace(/[Üü]/gu, (character) => (character === "Ü" ? "U" : "u"));
}

export function englishReferenceText(value: string): string {
  const ascii = transliterateTurkish(value);
  const upper = ascii.toUpperCase();
  const hasTranslatablePhrase = ORDERED_PHRASES.some(
    ([source, target]) => source !== target && replacePhrase(upper, source, target) !== upper,
  );
  if (!TURKISH_CHARACTERS.test(value) && !hasTranslatablePhrase) return value;

  let translated = upper;
  for (const [source, target] of ORDERED_PHRASES) {
    translated = replacePhrase(translated, source, target);
  }
  translated = translated
    .replace(/\bHES\b/gu, "HYDROELECTRIC POWER PLANT")
    .replace(/\bGES\b/gu, "SOLAR POWER PLANT")
    .replace(/\bJES\b/gu, "GEOTHERMAL POWER PLANT")
    .replace(/\bAAT\b/gu, "WASTEWATER TREATMENT PLANT")
    .replace(/\bOSB\b/gu, "ORGANISED INDUSTRIAL ZONE")
    .replace(/\bOG\b/gu, "MV")
    .replace(/\bAG\b/gu, "LV");
  return translated.replace(/\s+/gu, " ").replace(/\s+([,.)])/gu, "$1").trim();
}
