/**
 * Classifies a raw, source-printed location string from a Gersan catalogue
 * (customer/project "location" fields) as either a Türkiye city/region or a
 * foreign country. Built from the actual distinct location values observed
 * in the Busbar and Earthing & Lightning source data (references.json) —
 * every alias below was verified against a real catalogue row, not guessed.
 *
 * This never rewrites the source string itself — it only classifies it for
 * tab placement and produces a normalised label for filter dropdowns.
 */

export type ResolvedLocation =
  | Readonly<{ kind: "turkiye"; display: string }>
  | Readonly<{ kind: "country"; display: string }>
  | Readonly<{ kind: "unknown" }>;

const TURKIYE_ALIASES: Record<string, string> = {
  "İSTANBUL": "İstanbul",
  ISTANBUL: "İstanbul",
  "GAZİANTEP": "Gaziantep",
  GAZIANTEP: "Gaziantep",
  "İZMİR": "İzmir",
  IZMIR: "İzmir",
  BURSA: "Bursa",
  "KOCAELİ": "Kocaeli",
  KOCAELI: "Kocaeli",
  "İZMİT": "İzmit",
  IZMIT: "İzmit",
  KONYA: "Konya",
  "ANKARA KONYA": "Ankara",
  ANKARA: "Ankara",
  "TEKİRDAĞ": "Tekirdağ",
  TEKIRDAG: "Tekirdağ",
  "ÇORLU": "Çorlu",
  CORLU: "Çorlu",
  ZONGULDAK: "Zonguldak",
  "MANİSA": "Manisa",
  MANISA: "Manisa",
  ADANA: "Adana",
  "KAYSERİ": "Kayseri",
  KAYSERI: "Kayseri",
  "K.MARAŞ": "Kahramanmaraş",
  KAHRAMANMARAS: "Kahramanmaraş",
  "KAHRAMANMARAŞ": "Kahramanmaraş",
  AYDIN: "Aydın",
  "AYDİN": "Aydın",
  HATAY: "Hatay",
  ".HATAY": "Hatay",
  "İSKENDERUN": "İskenderun",
  ISKENDERUN: "İskenderun",
  SAKARYA: "Sakarya",
  ANTALYA: "Antalya",
  "ŞANLIURFA": "Şanlıurfa",
  SANLIURFA: "Şanlıurfa",
  "ESKİŞEHİR": "Eskişehir",
  ESKISEHIR: "Eskişehir",
  "MERSİN": "Mersin",
  MERSIN: "Mersin",
  "DENİZLİ": "Denizli",
  DENIZLI: "Denizli",
  BALIKESIR: "Balıkesir",
  "BALIKESİR": "Balıkesir",
  AFYON: "Afyonkarahisar",
  "AFYONKARAHİSAR": "Afyonkarahisar",
  AFYONKARAHISAR: "Afyonkarahisar",
  BARTIN: "Bartın",
  "BARTİN": "Bartın",
  "NİĞDE": "Niğde",
  NIGDE: "Niğde",
  "ÇANAKKALE": "Çanakkale",
  CANAKKALE: "Çanakkale",
  "SİVAS": "Sivas",
  SIVAS: "Sivas",
  "EDİRNE": "Edirne",
  EDIRNE: "Edirne",
  "ÇANKIRI": "Çankırı",
  CANKIRI: "Çankırı",
  "MUĞLA": "Muğla",
  MUGLA: "Muğla",
  VAN: "Van",
  YALOVA: "Yalova",
  ERZURUM: "Erzurum",
  "UŞAK": "Uşak",
  USAK: "Uşak",
  BOLU: "Bolu",
  "ERZİNCAN": "Erzincan",
  ERZINCAN: "Erzincan",
  "AĞRI": "Ağrı",
  AGRI: "Ağrı",
  KILIS: "Kilis",
  "KİLİS": "Kilis",
  "RİZE": "Rize",
  RIZE: "Rize",
  YOZGAT: "Yozgat",
  ARDAHAN: "Ardahan",
  TRABZON: "Trabzon",
  "DÜZCE": "Düzce",
  DUZCE: "Düzce",
  "SİİRT": "Siirt",
  SIIRT: "Siirt",
  KARS: "Kars",
  AKSARAY: "Aksaray",
  "KIRKLARELİ": "Kırklareli",
  KIRKLARELI: "Kırklareli",
  "ELAZIĞ": "Elazığ",
  ELAZIG: "Elazığ",
  "KIRŞEHİR": "Kırşehir",
  KIRSEHIR: "Kırşehir",
  KARAMAN: "Karaman",
  "MARDİN": "Mardin",
  MARDIN: "Mardin",
  MALATYA: "Malatya",
  "ADIYAMAN": "Adıyaman",
  "ADİYAMAN": "Adıyaman",
  "DİYARBAKIR": "Diyarbakır",
  DIYARBAKIR: "Diyarbakır",
  "BİLECİK": "Bilecik",
  BILECIK: "Bilecik",
  "KÜTAHYA": "Kütahya",
  KUTAHYA: "Kütahya",
  OSMANIYE: "Osmaniye",
  "OSMANİYE": "Osmaniye",
  "ISPARTA": "Isparta",
  SAMSUN: "Samsun",
  BURDUR: "Burdur",
  "GİRESUN": "Giresun",
  GIRESUN: "Giresun",
  "NEVŞEHİR": "Nevşehir",
  NEVSEHIR: "Nevşehir",
  BATMAN: "Batman",
  "ÇORUM": "Çorum",
  CORUM: "Çorum",
  "KÜYAHYA": "Kütahya",
  KUYAHYA: "Kütahya",
  "BURSAA": "Bursa",
  "İST": "İstanbul",
  IST: "İstanbul",
  "İST.": "İstanbul",
  "IST.": "İstanbul",
  "ETİLER İSTANBUL": "İstanbul",
  ETILER: "İstanbul",
  ORDU: "Ordu",
  AMASYA: "Amasya",
  KIRIKKALE: "Kırıkkale",
  "BODRUM-MUĞLA": "Muğla",
  "BODRUM": "Muğla",
  "BİTLİS": "Bitlis",
  BITLIS: "Bitlis",
  "ALANYA-ANTALYA": "Antalya",
  ALANYA: "Antalya",
  "İNEGÖL": "İnegöl",
  INEGOL: "İnegöl",
  "BİNGÖL": "Bingöl",
  BINGOL: "Bingöl",
  "Ç.KALE": "Çanakkale",
  "AKŞEHİR": "Akşehir",
  AKSEHIR: "Akşehir",
  "TİRE": "Tire",
  TIRE: "Tire",
  "KOCAELİ PROJESİ": "Kocaeli",
  "SİVAS (OZON TEKSTİL)": "Sivas",
};

const COUNTRY_ALIASES: Record<string, string> = {
  UAE: "UAE",
  "U.A.E": "UAE",
  "U.A.E.": "UAE",
  "UAE.": "UAE",
  "DUBAI/UAE": "UAE",
  "DUBAI/ U.A.E": "UAE",
  "DUBAI -UAE": "UAE",
  "DUBAI DUBAI,UAE": "UAE",
  DUBAI: "UAE",
  "DUBAİ": "UAE",
  ABUDHABI: "UAE",
  "ABU DHABI": "UAE",
  SHARJAH: "UAE",
  "SHARJ5 AH": "UAE",
  "UMM AL QUWAIN": "UAE",
  "RAS AL": "UAE",
  KHAIMAH: "UAE",
  "ADDUBAF.AI/UAE": "UAE",
  "AFDUBAI/UAE": "UAE",
  BANGLADESH: "Bangladesh",
  BANGLADASH: "Bangladesh",
  INDIA: "India",
  "BANCLORE /INDIA": "India",
  "CHENNAI / INDIA": "India",
  QATAR: "Qatar",
  "DOHA/ QATAR": "Qatar",
  "COLOMBİA": "Colombia",
  COLOMBIA: "Colombia",
  "İSRAİL": "Israel",
  ISRAIL: "Israel",
  ISRAEL: "Israel",
  "K.S.A.": "Saudi Arabia",
  "K.S.A": "Saudi Arabia",
  "SAUDI ARABIA": "Saudi Arabia",
  MADINAH: "Saudi Arabia",
  RUSYA: "Russia",
  RUSSIA: "Russia",
  "HANTY MANSISKY": "Russia",
  SAMARA: "Russia",
  "TATARİSTAN": "Russia",
  TATARISTAN: "Russia",
  MEXICO: "Mexico",
  GERMANY: "Germany",
  "ÖZBEKİSTAN": "Uzbekistan",
  OZBEKISTAN: "Uzbekistan",
  UZBEKISTAN: "Uzbekistan",
  MALTA: "Malta",
  AZERBAYCAN: "Azerbaijan",
  AZERBAIJAN: "Azerbaijan",
  "KAZAKİSTAN": "Kazakhstan",
  KAZAKISTAN: "Kazakhstan",
  KAZAKHSTAN: "Kazakhstan",
  NORWAY: "Norway",
  IRAK: "Iraq",
  IRAQ: "Iraq",
  "IN NORTH KUWAIT": "Kuwait",
  IRAN: "Iran",
  "İRAN": "Iran",
  "UK / IRELAND": "UK / Ireland",
  IRELAND: "UK / Ireland",
  PAKISTAN: "Pakistan",
  KIBRIS: "Cyprus",
  CYPRUS: "Cyprus",
  ROMANYA: "Romania",
  ROMANIA: "Romania",
  POLAND: "Poland",
  "CEZAYİR": "Algeria",
  CEZAYIR: "Algeria",
  "NORTH ALGERIA": "Algeria",
  ALGERIA: "Algeria",
  BULGARIA: "Bulgaria",
  "TÜRKMENİSTAN": "Turkmenistan",
  TURKMENISTAN: "Turkmenistan",
  "NİJERYA": "Nigeria",
  NIJERYA: "Nigeria",
  NICERIA: "Nigeria",
  NIGERIA: "Nigeria",
  UKRAINE: "Ukraine",
  UKRAYNA: "Ukraine",
  HOLLAND: "Netherlands",
  HOLLANDA: "Netherlands",
  NETHERLANDS: "Netherlands",
  LIBYA: "Libya",
  "LİBYA": "Libya",
  "MACARİSTAN": "Hungary",
  MACARISTAN: "Hungary",
  HUNGARY: "Hungary",
  "MISIR": "Egypt",
  EGYPT: "Egypt",
  "GÜRCİSTAN": "Georgia",
  GURCISTAN: "Georgia",
  GEORGIA: "Georgia",
  "AZERBAIJAN, GEORGIA, TURKIYE": "Azerbaijan, Georgia, Türkiye",
  "SRI LANKA": "Sri Lanka",
  "YUNANİSTAN": "Greece",
  YUNANISTAN: "Greece",
  GREECE: "Greece",
  OMAN: "Oman",
  "SULTANATE OF OMAN": "Oman",
  "MUSCAT- OMAN": "Oman",
  SINGAPUR: "Singapore",
  SINGAPORE: "Singapore",
  CAMEROUN: "Cameroon",
  CAMEROON: "Cameroon",
  LETONYA: "Latvia",
  LATVIA: "Latvia",
  TANZANIA: "Tanzania",
  MAURITIUS: "Mauritius",
  "LÜBNAN": "Lebanon",
  LUBNAN: "Lebanon",
  LEBANON: "Lebanon",
  BAHRAIN: "Bahrain",
  "BAHRAIN BAHRAIN": "Bahrain",
  SPAIN: "Spain",
  THAILAND: "Thailand",
  SYRIA: "Syria",
  LITHUANIA: "Lithuania",
  TUNISIA: "Tunisia",
  JORDAN: "Jordan",
  SUDAN: "Sudan",
  KUWAIT: "Kuwait",
  TURKIYE: "Türkiye",
  TURKEY: "Turkey",
  "TACİKİSTAN": "Tajikistan",
  TACIKISTAN: "Tajikistan",
  TAJIKISTAN: "Tajikistan",
  "AFGANİSTAN": "Afghanistan",
  AFGANISTAN: "Afghanistan",
  AFGHANISTAN: "Afghanistan",
  MOLDOVA: "Moldova",
  "MALİ": "Mali",
  MALI: "Mali",
  KKTC: "Northern Cyprus",
  "NORTHERN CYPRUS": "Northern Cyprus",
};

function normalise(value: string): string {
  return value.trim().replace(/\s+/g, " ").toUpperCase();
}

/**
 * Ukrainian display names for every canonical country value produced by
 * COUNTRY_ALIASES above — a closed, deterministic dictionary (no external
 * translation API), following standard Ukrainian country-name conventions.
 * Keyed by the English canonical value (COUNTRY_ALIASES' right-hand side),
 * never by the raw source string, so it stays a pure display-layer lookup.
 */
const UKRAINIAN_COUNTRY_NAMES: Record<string, string> = {
  UAE: "Об’єднані Арабські Емірати",
  Bangladesh: "Бангладеш",
  India: "Індія",
  Qatar: "Катар",
  Colombia: "Колумбія",
  Israel: "Ізраїль",
  "Saudi Arabia": "Саудівська Аравія",
  Russia: "Росія",
  Mexico: "Мексика",
  Germany: "Німеччина",
  Uzbekistan: "Узбекистан",
  Malta: "Мальта",
  Azerbaijan: "Азербайджан",
  Kazakhstan: "Казахстан",
  Norway: "Норвегія",
  Iraq: "Ірак",
  "UK / Ireland": "Велика Британія / Ірландія",
  Iran: "Іран",
  Pakistan: "Пакистан",
  Cyprus: "Кіпр",
  Romania: "Румунія",
  Poland: "Польща",
  Algeria: "Алжир",
  Bulgaria: "Болгарія",
  Turkmenistan: "Туркменістан",
  Nigeria: "Нігерія",
  Ukraine: "Україна",
  Netherlands: "Нідерланди",
  Libya: "Лівія",
  Hungary: "Угорщина",
  Egypt: "Єгипет",
  Georgia: "Грузія",
  "Azerbaijan, Georgia, Türkiye": "Азербайджан, Грузія, Туреччина",
  "Sri Lanka": "Шрі-Ланка",
  Greece: "Греція",
  Oman: "Оман",
  Singapore: "Сінгапур",
  Cameroon: "Камерун",
  Latvia: "Латвія",
  Tanzania: "Танзанія",
  Mauritius: "Маврикій",
  Lebanon: "Ліван",
  Bahrain: "Бахрейн",
  Spain: "Іспанія",
  Thailand: "Таїланд",
  Syria: "Сирія",
  Lithuania: "Литва",
  Tunisia: "Туніс",
  Jordan: "Йорданія",
  Sudan: "Судан",
  Kuwait: "Кувейт",
  Türkiye: "Туреччина",
  Turkey: "Туреччина",
  Tajikistan: "Таджикистан",
  Afghanistan: "Афганістан",
  Moldova: "Молдова",
  Mali: "Малі",
  "Northern Cyprus": "Північний Кіпр",
};

/** Returns the Ukrainian display name for a canonical (English) country
 * value, falling back to the input unchanged if it isn't in the dictionary
 * (defensive only — every COUNTRY_ALIASES value above has an entry). */
export function ukrainianCountryDisplay(canonicalCountry: string): string {
  return UKRAINIAN_COUNTRY_NAMES[canonicalCountry] ?? canonicalCountry;
}

/**
 * Ukrainian display names for every canonical Türkiye city/region value
 * produced by TURKIYE_ALIASES above — deterministic transliteration/known
 * exonyms (e.g. İstanbul -> Стамбул), not machine translation.
 */
const UKRAINIAN_TURKIYE_NAMES: Record<string, string> = {
  "İstanbul": "Стамбул",
  Gaziantep: "Газіантеп",
  "İzmir": "Ізмір",
  Bursa: "Бурса",
  Kocaeli: "Коджаелі",
  "İzmit": "Ізміт",
  Konya: "Конья",
  Ankara: "Анкара",
  "Tekirdağ": "Текірдаг",
  "Çorlu": "Чорлу",
  Zonguldak: "Зонгулдак",
  Manisa: "Маніса",
  Adana: "Адана",
  Kayseri: "Кайсері",
  "Kahramanmaraş": "Кахраманмараш",
  "Aydın": "Айдин",
  Hatay: "Хатай",
  "İskenderun": "Іскендерун",
  Sakarya: "Сакар’я",
  Antalya: "Анталія",
  "Şanlıurfa": "Шанлиурфа",
  "Eskişehir": "Ескішехір",
  Mersin: "Мерсін",
  Denizli: "Денізлі",
  "Balıkesir": "Баликесір",
  Afyonkarahisar: "Афьонкарахісар",
  "Bartın": "Бартин",
  "Niğde": "Нігде",
  "Çanakkale": "Чанаккале",
  Sivas: "Сівас",
  Edirne: "Едірне",
  "Çankırı": "Чанкири",
  "Muğla": "Мугла",
  Van: "Ван",
  Yalova: "Ялова",
  Erzurum: "Ерзурум",
  "Uşak": "Ушак",
  Bolu: "Болу",
  Erzincan: "Ерзінджан",
  "Ağrı": "Агри",
  Kilis: "Кіліс",
  Rize: "Різе",
  Yozgat: "Йозгат",
  Ardahan: "Ардаган",
  Trabzon: "Трабзон",
  "Düzce": "Дюздже",
  Siirt: "Сіірт",
  Kars: "Карс",
  Aksaray: "Аксарай",
  "Kırklareli": "Киркларелі",
  "Elazığ": "Елязиг",
  "Kırşehir": "Киршехір",
  Karaman: "Караман",
  Mardin: "Мардін",
  Malatya: "Малатья",
  "Adıyaman": "Адияман",
  "Diyarbakır": "Діярбакир",
  Bilecik: "Біледжік",
  "Kütahya": "Кютах’я",
  Osmaniye: "Османіє",
  Isparta: "Іспарта",
  Samsun: "Самсун",
  Burdur: "Бурдур",
  Giresun: "Гіресун",
  "Nevşehir": "Невшехір",
  Batman: "Батман",
  "Çorum": "Чорум",
  "İnegöl": "Інегьол",
  "Bingöl": "Бінгьол",
  "Akşehir": "Акшехір",
  Tire: "Тіре",
};

/** Returns the Ukrainian display name for a canonical Türkiye city/region
 * value, falling back to the input unchanged if it isn't in the dictionary
 * (defensive only — every TURKIYE_ALIASES value above has an entry). */
export function ukrainianTurkiyeDisplay(canonicalDisplay: string): string {
  return UKRAINIAN_TURKIYE_NAMES[canonicalDisplay] ?? canonicalDisplay;
}

export function resolveReferenceLocation(raw: string): ResolvedLocation {
  const key = normalise(raw);
  if (!key) return { kind: "unknown" };

  const turkiye = TURKIYE_ALIASES[key];
  if (turkiye) return { kind: "turkiye", display: turkiye };

  const country = COUNTRY_ALIASES[key];
  if (country) return { kind: "country", display: country };

  return { kind: "unknown" };
}

/**
 * Well-documented, unambiguous national utility/energy entities that appear
 * as bare abbreviations in compound "owner" fields (e.g. Cable Management's
 * "OMAN : PDO", "DEWA") without a country name printed alongside them. Only
 * entities tied to exactly one country are included — ambiguous engineering
 * contractors and multinational operators are deliberately left unresolved.
 */
const GULF_ENTITY_ALIASES: Record<string, string> = {
  DEWA: "UAE",
  RTA: "UAE",
  ADNOC: "UAE",
  FEWA: "UAE",
  DUBAL: "UAE",
  TRANSCO: "UAE",
  ADCO: "UAE",
  TAKREER: "UAE",
  ENOC: "UAE",
  EMAL: "UAE",
  SEWA: "UAE",
  ADWEA: "UAE",
  NAKHEEL: "UAE",
  GASCO: "UAE",
  FERTIL: "UAE",
  KAHRAMAA: "Qatar",
  QATALUM: "Qatar",
  KOC: "Kuwait",
  MEW: "Kuwait",
  OXY: "Oman",
  PDO: "Oman",
  PD0: "Oman",
  MEDC: "Oman",
  RAECO: "Oman",
  OOCEP: "Oman",
  OETC: "Oman",
  ALBA: "Bahrain",
  TURKMENGAS: "Turkmenistan",
  SONATRACH: "Algeria",
  "AGIP KCO": "Kazakhstan",
  ONGC: "India",
};

/**
 * For compound / free-text fields (e.g. Cable Management's "owner" column,
 * which mixes country names with client-entity abbreviations like "DEWA" or
 * "OMAN : PDO") — resolves a country from any recognisable token or known
 * entity name inside the string. Returns undefined rather than guessing when
 * nothing recognisable is present.
 */
export function resolveOwnerCountry(raw: string): string | undefined {
  const normalised = normalise(raw);
  if (!normalised) return undefined;

  for (const [key, value] of Object.entries(COUNTRY_ALIASES)) {
    if (key.includes(" ") && normalised.includes(key)) return value;
  }

  const tokens = normalised.split(/[^\p{L}0-9.]+/u).filter(Boolean);
  for (const token of tokens) {
    if (COUNTRY_ALIASES[token]) return COUNTRY_ALIASES[token];
    if (GULF_ENTITY_ALIASES[token]) return GULF_ENTITY_ALIASES[token];
  }

  return undefined;
}
